version: "3.7"

services:
  pasarela:
    build: .
    ports:
      - "8090:8090"

  estaciones:
    build: ../estacionesLopezGuevara/
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:example@mongo:27017/estaciones?authSource=admin
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq

  usuarios:
    build: ../usuarios/
    ports:
      - "5000:5000"
    environment:
      - MONGO_CONNECTION_STRING_USUARIOS=mongodb://root:example@mongo:27017/usuarios.net?authSource=admin
      - MONGO_CONNECTION_STRING_CODIGOS=mongodb://root:example@mongo:27017/codigos.net?authSource=admin
      - ASPNETCORE_KESTREL__ENDPOINTS__HTTP__URL=http://+:5000
    depends_on:
      - mongo

  alquileres:
    build: ../alquileresLopezGuevara/
    ports:
      - "8080:8080"
    environment:
      - DATABASE_CONNECTION_STRING=mongodb://root:example@mongo:27017/usuarios?authSource=admin
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "9000:8081"
    environment:
      ME_CONFIG_BASICAUTH: 0
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo


  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo_data:

